/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/features/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-dim': '#0049c2',
        'surface-container': '#eaeef1',
        'on-tertiary-fixed': '#311c00',
        'inverse-primary': '#618bff',
        'surface': '#f7f9fb',
        'primary-container': '#acbfff',
        'surface-variant': '#dde3e7',
        'on-tertiary': '#fff7f3',
        'inverse-surface': '#0b0f10',
        'surface-dim': '#d3dbdf',
        'on-primary-fixed-variant': '#003da4',
        'tertiary-dim': '#764900',
        'secondary': '#006d4a',
        'on-surface': '#2d3337',
        'surface-container-high': '#e3e9ec',
        'secondary-dim': '#005f40',
        'on-tertiary-fixed-variant': '#5b3800',
        'surface-container-low': '#f1f4f6',
        'tertiary': '#865400',
        'outline': '#757c7f',
        'error': '#ac3434',
        'on-error-container': '#65000b',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#acbfff',
        'surface-bright': '#f7f9fb',
        'on-tertiary-container': '#4f3000',
        'tertiary-fixed-dim': '#ee9800',
        'tertiary-fixed': '#fea619',
        'error-dim': '#70030f',
        'on-secondary-container': '#005e3f',
        'secondary-fixed': '#6ffbbe',
        'background': '#f7f9fb',
        'on-primary-fixed': '#002265',
        'outline-variant': '#acb3b7',
        'on-secondary-fixed-variant': '#006947',
        'primary': '#0053dc',
        'primary-fixed-dim': '#98b1ff',
        'on-error': '#fff7f6',
        'inverse-on-surface': '#9a9d9f',
        'secondary-container': '#6ffbbe',
        'on-secondary': '#e6ffee',
        'error-container': '#f56965',
        'on-surface-variant': '#596063',
        'on-secondary-fixed': '#004930',
        'surface-tint': '#0053dc',
        'on-primary': '#faf8ff',
        'on-background': '#2d3337',
        'tertiary-container': '#fea619',
        'on-primary-container': '#003591',
        'secondary-fixed-dim': '#5fedb0',
        'surface-container-highest': '#dde3e7',

        // Pathfinder roadmap status colors
        'status-completed': '#10b981',
        'status-progress': '#2563eb',
        'status-locked': '#64748b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        serif: ['Source Serif 4', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
